# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  DreamRenderer_config = debug
  DreamNote_config = debug
endif
ifeq ($(config),release)
  DreamRenderer_config = release
  DreamNote_config = release
endif
ifeq ($(config),dist)
  DreamRenderer_config = dist
  DreamNote_config = dist
endif

PROJECTS := DreamRenderer DreamNote

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

DreamRenderer:
ifneq (,$(DreamRenderer_config))
	@echo "==== Building DreamRenderer ($(DreamRenderer_config)) ===="
	@${MAKE} --no-print-directory -C DreamRenderer -f Makefile config=$(DreamRenderer_config)
endif

DreamNote:
ifneq (,$(DreamNote_config))
	@echo "==== Building DreamNote ($(DreamNote_config)) ===="
	@${MAKE} --no-print-directory -C Notes -f Makefile config=$(DreamNote_config)
endif

clean:
	@${MAKE} --no-print-directory -C DreamRenderer -f Makefile clean
	@${MAKE} --no-print-directory -C Notes -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DreamRenderer"
	@echo "   DreamNote"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"